ShopWellcome         		: Willkommen in unserem Shop
NoProducts           		: keine Produkte gefunden

Submit				 		: Absenden
Back				 		: Zurück

Admin                		: Verwaltung
AdminUsers           		: Nutzer verwalten
AdminProducts        		: Produkte verwalten
AdminAssocs          		: Assoziationen verwalten

Search               		: Suchen
RelatedProducts      		: Zugehörige Produkte
AddNewProduct        		: Neues Produkt hinzufügen
AddNewAssoc          		: Neue Kategorie-Assoziation
AddNewUser           		: Neuen Nutzer hinzufügen
BuyProduct           		: Kaufen
BoughtProducts	 	 		: Gekaufte Produkte
ProductBought p@Product     : Produkt gekauft #{show $ getProductTitle p}
Username			 		: Nutzername
Actions				 		: Aktionen

UserAlreadyExisting  		: Nutzer existiert bereits
InvalidInput		 		: Falsche Eingabe
UserCreated	name@Text	 	: Benutzer erstellt: #{name}
LoginAs	name@Text	 		: Eingeloggt als: #{name}
PleaseLogin 				: Bitte einloggen!
InvalidUser					: Ungültiger Nutzer
