ShopWellcome         		: Willkommen bei Axt und Degen
RecommendedProducts			: Empfohlene Produkte
ProductCatalog				: Produkt Katalog
NoProducts           		: keine Produkte gefunden

Submit				 		: Absenden
Back				 		: Zurück

Admin                		: Verwaltung
AdminUsers           		: Nutzer verwalten
AdminProducts        		: Produkte verwalten
AdminAssocs          		: Assoziationen verwalten

Search               		: Suchen
RelatedProducts      		: Zugehörige Produkte
AddNewProduct        		: Neues Produkt hinzufügen
AddNewAssoc          		: Neue Kategorie-Assoziation
AddNewUser           		: Neuen Nutzer hinzufügen
BuyProduct           		: Kaufen
BoughtProducts	 	 		: Gekaufte Produkte
ProductBought p@Product     : Produkt gekauft #{show $ getProductTitle p}
ProductNotFound				: Produkt nicht gefunden
ProductAdded 				: Produkt hinzugefügt
Username			 		: Nutzername
Actions				 		: Aktionen

UserAlreadyExisting  		: Nutzer existiert bereits
InvalidInput		 		: Falsche Eingabe
UserCreated	name@Text	 	: Benutzer erstellt: #{name}
LoginAs	name@Text	 		: Eingeloggt als: #{name}
LoggedOut					: Abgemeldet
NotLoggedIn			 		: Nicht eingeloggt
Logout					 	: Abmelden
Login					 	: Anmelden
PleaseLogin 				: Bitte einloggen!
InvalidUser					: Ungültiger Nutzer
UserHistoryCleared			: Kauf-Verlauf gelöscht
UserHistoryEntryDeleted		: Kauf-Eintrag gelöscht


ProductSize 				: Größe
ProductSizes				: Größen
ProductColor				: Farbe
ProductColors 				: Farben
ProductTitle				: Titel
ProductSlot			 		: Ausrüstungsplatz
ProductCategories			: Kategorien
ProductDescription 			: Beschreibung

ProductRequirements			: Anforderungen
ProductBoni					: Boni
AttribStrength				: Stärke
AttribIntelligence			: Intelligenz
AttribDexterity				: Geschicklichkeit
AttribStamina				: Ausdauer
